apiVersion: v1
kind: Service
metadata:
    name: "freetrialaks"
    labels:
        app: "freetrialaks"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "freetrialaks"